package ProyectoTBDD2_AndresCruz_StephanieMartinez;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class MenuPrincipal extends javax.swing.JFrame {

    Persona persona;
    DatosLegales datosLegales;
    Curriculum curriculum;
    ExperienciaLaboral experiencia;
    DatosAcademicos datosacademicos;
    DatosSanitarios datossanitarios;
    Empresas empresa;

    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        RecuperacionBD();
        for (int i = 0; i < tiposdetrabajo.size(); i++) {
            System.out.println(tiposdetrabajo.get(i).getNombreCategoria());
        }
    }

    public boolean validarEspacio() {
        boolean condicion = false;
        String contrasenaValidar = new String(jpf_contrasena.getPassword());
        if (jtf_usuario.getText().isEmpty() || contrasenaValidar.isEmpty()) {
            condicion = true;
        }
        return condicion;
    }
    
    public void RecuperacionBD(){
        try {
            personas=(ArrayList<Persona>) servidor.getPersonas(null);
            System.out.println("persona");
            empresas= (ArrayList<Empresas>) servidor.getEmpresa(null);
            System.out.println("empresa");
            tiposdetrabajo= (ArrayList<TipoTrabajo>) servidor.getTipoTrabajo(null);
            System.out.println("trabajos");
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jpf_contrasena = new javax.swing.JPasswordField();
        jb_aceptarLogin = new javax.swing.JButton();
        jb_salirLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtf_usuario = new javax.swing.JTextField();
        jd_datosPersonales = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jtp_informacionPersonal = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtf_apellidoPersonal = new javax.swing.JTextField();
        jtf_nombrePersonal = new javax.swing.JTextField();
        jtf_nacionalidadPersonal = new javax.swing.JTextField();
        jrb_femeninoPersonal = new javax.swing.JRadioButton();
        jrb_masculinoPersonal = new javax.swing.JRadioButton();
        jdc_nacimientoPersonal = new com.toedter.calendar.JDateChooser();
        jtf_telefonoPersonal = new javax.swing.JTextField();
        jtf_correoPersonal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_direccionPersonal = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jrb_siFamiliares = new javax.swing.JRadioButton();
        jrb_noFamiliares = new javax.swing.JRadioButton();
        jLabel17 = new javax.swing.JLabel();
        jtf_parentescoFamiliares = new javax.swing.JTextField();
        jtf_nombreFamiliares = new javax.swing.JTextField();
        jtf_idFamiliares = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jtf_identidadLegal = new javax.swing.JTextField();
        jrb_siAntecedenteLegal = new javax.swing.JRadioButton();
        jrb_siLicenciaLegal = new javax.swing.JRadioButton();
        jrb_siServicioLegal = new javax.swing.JRadioButton();
        jrb_siCasadoLegal = new javax.swing.JRadioButton();
        jrb_siVisaLegal = new javax.swing.JRadioButton();
        jrb_noAntecedenteLegal = new javax.swing.JRadioButton();
        jrb_noLicenciaLegal = new javax.swing.JRadioButton();
        jrb_noServicioLegal = new javax.swing.JRadioButton();
        jrb_noCasadoLegal = new javax.swing.JRadioButton();
        jrb_noVisaLegal = new javax.swing.JRadioButton();
        jLabel46 = new javax.swing.JLabel();
        jrb_siEdadLegal = new javax.swing.JRadioButton();
        jrb_noEdadLegal = new javax.swing.JRadioButton();
        jb_guardarPersonal = new javax.swing.JButton();
        jtf_nombrePersonal1 = new javax.swing.JTextField();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        bg_antecedentePenal = new javax.swing.ButtonGroup();
        bg_licencia = new javax.swing.ButtonGroup();
        bg_servicioMilitar = new javax.swing.ButtonGroup();
        bg_casado = new javax.swing.ButtonGroup();
        bg_visa = new javax.swing.ButtonGroup();
        jd_datosProfesionales = new javax.swing.JDialog();
        jLabel24 = new javax.swing.JLabel();
        jtb_datosProfesionales = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_puestoProfesional = new javax.swing.JTextArea();
        jtf_salarioProfesional = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_idiomasProfesional = new javax.swing.JTextArea();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jrb_siContratoProfesional = new javax.swing.JRadioButton();
        jrb_noContratoProfesional = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jtf_aniosProfesional = new javax.swing.JTextField();
        jtf_trabajoProfesional = new javax.swing.JTextField();
        jtf_puestoProfesional = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jta_otrosEstudiosProfesional = new javax.swing.JTextArea();
        jrb_siEstudianteProfesional = new javax.swing.JRadioButton();
        jrb_noEstudianteProfesional = new javax.swing.JRadioButton();
        jtf_especializacionProfesional = new javax.swing.JTextField();
        jcb_gradoProfesional = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jrb_siAlergiasProfesional = new javax.swing.JRadioButton();
        jrb_siRespiratorioProfesional = new javax.swing.JRadioButton();
        jrb_siCardiacoProfesional = new javax.swing.JRadioButton();
        jrb_siMentalProfesional = new javax.swing.JRadioButton();
        jrb_noAlergiasProfesional = new javax.swing.JRadioButton();
        jrb_noRespiratorioProfesional = new javax.swing.JRadioButton();
        jrb_noCardiacoProfesional = new javax.swing.JRadioButton();
        jrb_noMentalProfesional = new javax.swing.JRadioButton();
        jb_guardarProfesional = new javax.swing.JButton();
        bg_contrato = new javax.swing.ButtonGroup();
        bg_estudiante = new javax.swing.ButtonGroup();
        bg_alergia = new javax.swing.ButtonGroup();
        bg_respiratorio = new javax.swing.ButtonGroup();
        bg_cardiaco = new javax.swing.ButtonGroup();
        bg_mental = new javax.swing.ButtonGroup();
        bg_mayor = new javax.swing.ButtonGroup();
        jd_menuAgencia = new javax.swing.JDialog();
        jLabel47 = new javax.swing.JLabel();
        jb_crearEmpresa = new javax.swing.JButton();
        jd_crearEmpresa = new javax.swing.JDialog();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jtf_cifEmpresa = new javax.swing.JTextField();
        jtf_nombreEmpresa = new javax.swing.JTextField();
        jtf_ceoEmpresa = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jta_direccionEmpresa = new javax.swing.JTextArea();
        jcb_categoriaEmpresa = new javax.swing.JComboBox<>();
        jb_guardarEmpresas = new javax.swing.JButton();
        jb_subecurriculum = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        jb_login = new javax.swing.JButton();

        jd_login.setTitle("Login");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Login");

        jpf_contrasena.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jb_aceptarLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jb_aceptarLogin.setText("Aceptar");
        jb_aceptarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_aceptarLoginMouseClicked(evt);
            }
        });

        jb_salirLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jb_salirLogin.setText("Salir");
        jb_salirLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirLoginMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("Contraseña");

        jtf_usuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jpf_contrasena))
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jb_aceptarLogin)
                        .addGap(52, 52, 52)
                        .addComponent(jb_salirLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jpf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_aceptarLogin)
                    .addComponent(jb_salirLogin))
                .addGap(44, 44, 44))
        );

        jd_datosPersonales.setTitle("Datos Personales");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel5.setText("Crea tu perfil");

        jtp_informacionPersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Nombre");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Apellido");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Nacionalidad");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Género");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Fecha de nacimiento");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Teléfono");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Correo");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Dirección");

        jtf_apellidoPersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_nombrePersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_nacionalidadPersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        buttonGroup1.add(jrb_femeninoPersonal);
        jrb_femeninoPersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_femeninoPersonal.setText("Femenino");

        buttonGroup1.add(jrb_masculinoPersonal);
        jrb_masculinoPersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_masculinoPersonal.setText("Masculino");

        jtf_telefonoPersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_correoPersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jta_direccionPersonal.setColumns(20);
        jta_direccionPersonal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jta_direccionPersonal.setRows(5);
        jScrollPane1.setViewportView(jta_direccionPersonal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(jdc_nacimientoPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtf_nombrePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(51, 51, 51))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(22, 22, 22)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_nacionalidadPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_apellidoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jrb_femeninoPersonal)
                                    .addGap(18, 18, 18)
                                    .addComponent(jrb_masculinoPersonal))))
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGap(22, 22, 22)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtf_correoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtf_telefonoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jtf_nombrePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtf_apellidoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtf_nacionalidadPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jrb_femeninoPersonal)
                            .addComponent(jrb_masculinoPersonal))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10))
                    .addComponent(jdc_nacimientoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtf_telefonoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jtf_correoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jtp_informacionPersonal.addTab("Información personal", jPanel1);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Nombre");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Parentesco");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("¿Es su familiar usuario de agencia?");

        buttonGroup2.add(jrb_siFamiliares);
        jrb_siFamiliares.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siFamiliares.setText("Si");

        buttonGroup2.add(jrb_noFamiliares);
        jrb_noFamiliares.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noFamiliares.setText("No");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("ID");

        jtf_parentescoFamiliares.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_nombreFamiliares.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_idFamiliares.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(48, 48, 48)
                        .addComponent(jtf_nombreFamiliares))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jtf_parentescoFamiliares))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel17)
                                    .addGap(26, 26, 26)
                                    .addComponent(jtf_idFamiliares, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel16))
                            .addGap(18, 18, 18)
                            .addComponent(jrb_siFamiliares))))
                .addGap(18, 18, 18)
                .addComponent(jrb_noFamiliares)
                .addGap(86, 86, 86))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtf_nombreFamiliares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtf_parentescoFamiliares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jrb_siFamiliares)
                    .addComponent(jrb_noFamiliares))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtf_idFamiliares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jtp_informacionPersonal.addTab("Datos familiares", jPanel2);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Número de identidad");

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("¿Tiene algún antecedente penal?");

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("¿Tiene licencia de conducir?");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("¿Ha hecho servicio militar?");

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("¿Está casado?");

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("¿Tiene Visa?");

        jtf_identidadLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        bg_antecedentePenal.add(jrb_siAntecedenteLegal);
        jrb_siAntecedenteLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siAntecedenteLegal.setText("Si");

        bg_licencia.add(jrb_siLicenciaLegal);
        jrb_siLicenciaLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siLicenciaLegal.setText("Si");

        bg_servicioMilitar.add(jrb_siServicioLegal);
        jrb_siServicioLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siServicioLegal.setText("Si");

        bg_casado.add(jrb_siCasadoLegal);
        jrb_siCasadoLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siCasadoLegal.setText("Si");

        bg_visa.add(jrb_siVisaLegal);
        jrb_siVisaLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siVisaLegal.setText("Si");

        bg_antecedentePenal.add(jrb_noAntecedenteLegal);
        jrb_noAntecedenteLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noAntecedenteLegal.setText("No");

        bg_licencia.add(jrb_noLicenciaLegal);
        jrb_noLicenciaLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noLicenciaLegal.setText("No");

        bg_servicioMilitar.add(jrb_noServicioLegal);
        jrb_noServicioLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noServicioLegal.setText("No");

        bg_casado.add(jrb_noCasadoLegal);
        jrb_noCasadoLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noCasadoLegal.setText("No");

        bg_visa.add(jrb_noVisaLegal);
        jrb_noVisaLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noVisaLegal.setText("No");

        jLabel46.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel46.setText("Mayor de edad");

        bg_mayor.add(jrb_siEdadLegal);
        jrb_siEdadLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siEdadLegal.setText("Si");

        bg_mayor.add(jrb_noEdadLegal);
        jrb_noEdadLegal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noEdadLegal.setText("No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_siEdadLegal)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_noEdadLegal)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_identidadLegal, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel23))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jrb_siVisaLegal)
                                                .addGap(18, 18, 18)
                                                .addComponent(jrb_noVisaLegal))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jrb_siCasadoLegal)
                                                .addGap(18, 18, 18)
                                                .addComponent(jrb_noCasadoLegal))))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrb_siAntecedenteLegal)
                                        .addGap(10, 10, 10)
                                        .addComponent(jrb_noAntecedenteLegal))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrb_siLicenciaLegal)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrb_noLicenciaLegal))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrb_siServicioLegal)
                                        .addGap(18, 18, 18)
                                        .addComponent(jrb_noServicioLegal)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(116, 116, 116))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jtf_identidadLegal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(jrb_siEdadLegal)
                    .addComponent(jrb_noEdadLegal))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jrb_siAntecedenteLegal)
                        .addComponent(jrb_noAntecedenteLegal)))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jrb_siLicenciaLegal)
                    .addComponent(jrb_noLicenciaLegal))
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jrb_siServicioLegal)
                    .addComponent(jrb_noServicioLegal))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jrb_siCasadoLegal)
                    .addComponent(jrb_noCasadoLegal))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jrb_siVisaLegal)
                    .addComponent(jrb_noVisaLegal))
                .addGap(60, 60, 60))
        );

        jtp_informacionPersonal.addTab("Datos Legales", jPanel4);

        jb_guardarPersonal.setText("Guardar");
        jb_guardarPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarPersonalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_datosPersonalesLayout = new javax.swing.GroupLayout(jd_datosPersonales.getContentPane());
        jd_datosPersonales.getContentPane().setLayout(jd_datosPersonalesLayout);
        jd_datosPersonalesLayout.setHorizontalGroup(
            jd_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtp_informacionPersonal)
            .addGroup(jd_datosPersonalesLayout.createSequentialGroup()
                .addGroup(jd_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_datosPersonalesLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jLabel5))
                    .addGroup(jd_datosPersonalesLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jb_guardarPersonal)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_datosPersonalesLayout.setVerticalGroup(
            jd_datosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_datosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtp_informacionPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jb_guardarPersonal)
                .addContainerGap())
        );

        jtf_nombrePersonal1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jd_datosProfesionales.setTitle("Datos Profesionales");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel24.setText("Datos Profesionales");

        jtb_datosProfesionales.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Puesto deseado");

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Salario deseado");

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Contrato a tiempo completo");

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Idiomas ");

        jLabel29.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel29.setText("Escriba la lista de trabajos ");

        jLabel30.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel30.setText("separados por comas");

        jta_puestoProfesional.setColumns(20);
        jta_puestoProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jta_puestoProfesional.setRows(5);
        jScrollPane2.setViewportView(jta_puestoProfesional);

        jtf_salarioProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jta_idiomasProfesional.setColumns(20);
        jta_idiomasProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jta_idiomasProfesional.setRows(5);
        jScrollPane3.setViewportView(jta_idiomasProfesional);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel31.setText("Escriba la lista de idiomas ");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel32.setText("separados por comas");

        bg_contrato.add(jrb_siContratoProfesional);
        jrb_siContratoProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siContratoProfesional.setText("Si");

        bg_contrato.add(jrb_noContratoProfesional);
        jrb_noContratoProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noContratoProfesional.setText("No");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_siContratoProfesional)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_noContratoProfesional))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel25))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jtf_salarioProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel32)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel29)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel30)))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jtf_salarioProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jrb_siContratoProfesional)
                    .addComponent(jrb_noContratoProfesional))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel32))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jtb_datosProfesionales.addTab("Curriculum", jPanel5);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("Trabajo anterior");

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setText("Años de experiencia");

        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setText("Puesto anterior");

        jtf_aniosProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_trabajoProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_puestoProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(28, 28, 28)
                        .addComponent(jtf_aniosProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_puestoProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(18, 18, 18)
                        .addComponent(jtf_trabajoProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_aniosProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addGap(46, 46, 46)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jtf_trabajoProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jtf_puestoProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jtb_datosProfesionales.addTab("Experiencia Laboral", jPanel6);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel36.setText("Grado obtenido");

        jLabel37.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel37.setText("Especialización");

        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setText("Estudiante activo");

        jLabel39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel39.setText("Otros estudios");

        jLabel40.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel40.setText("Escriba la lista de estudios ");

        jLabel41.setFont(new java.awt.Font("Arial", 0, 9)); // NOI18N
        jLabel41.setText("separados por comas");

        jta_otrosEstudiosProfesional.setColumns(20);
        jta_otrosEstudiosProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jta_otrosEstudiosProfesional.setRows(5);
        jScrollPane4.setViewportView(jta_otrosEstudiosProfesional);

        bg_estudiante.add(jrb_siEstudianteProfesional);
        jrb_siEstudianteProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siEstudianteProfesional.setText("Si");

        bg_estudiante.add(jrb_noEstudianteProfesional);
        jrb_noEstudianteProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noEstudianteProfesional.setText("No");

        jtf_especializacionProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jcb_gradoProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_gradoProfesional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Educación básica", "Educación secundaria", "Licenciatura o Ingeniería", "Maestría", "Doctorado" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel41)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jrb_siEstudianteProfesional)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_noEstudianteProfesional))
                    .addComponent(jtf_especializacionProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_gradoProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jcb_gradoProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jtf_especializacionProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jrb_siEstudianteProfesional)
                    .addComponent(jrb_noEstudianteProfesional))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel41))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jtb_datosProfesionales.addTab("Datos Académicos", jPanel7);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel42.setText("Alergias");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel43.setText("Problemas respiratorios");

        jLabel44.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel44.setText("Problemas cardíacos");

        jLabel45.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel45.setText("Problemas mentales");

        bg_alergia.add(jrb_siAlergiasProfesional);
        jrb_siAlergiasProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siAlergiasProfesional.setText("Si");

        bg_respiratorio.add(jrb_siRespiratorioProfesional);
        jrb_siRespiratorioProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siRespiratorioProfesional.setText("Si");

        bg_cardiaco.add(jrb_siCardiacoProfesional);
        jrb_siCardiacoProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siCardiacoProfesional.setText("Si");

        bg_mental.add(jrb_siMentalProfesional);
        jrb_siMentalProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_siMentalProfesional.setText("Si");

        bg_alergia.add(jrb_noAlergiasProfesional);
        jrb_noAlergiasProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noAlergiasProfesional.setText("No");

        bg_respiratorio.add(jrb_noRespiratorioProfesional);
        jrb_noRespiratorioProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noRespiratorioProfesional.setText("No");

        bg_cardiaco.add(jrb_noCardiacoProfesional);
        jrb_noCardiacoProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noCardiacoProfesional.setText("No");

        bg_mental.add(jrb_noMentalProfesional);
        jrb_noMentalProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jrb_noMentalProfesional.setText("No");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_siCardiacoProfesional)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_noCardiacoProfesional))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel43)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_siRespiratorioProfesional)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_noRespiratorioProfesional))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel42)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_siAlergiasProfesional)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_noAlergiasProfesional))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel45)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_siMentalProfesional)
                        .addGap(18, 18, 18)
                        .addComponent(jrb_noMentalProfesional)))
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jrb_siAlergiasProfesional)
                    .addComponent(jrb_noAlergiasProfesional))
                .addGap(33, 33, 33)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(jrb_siRespiratorioProfesional)
                    .addComponent(jrb_noRespiratorioProfesional))
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jrb_siCardiacoProfesional)
                    .addComponent(jrb_noCardiacoProfesional))
                .addGap(41, 41, 41)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(jrb_siMentalProfesional)
                    .addComponent(jrb_noMentalProfesional))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        jtb_datosProfesionales.addTab("Datos Sanitarios", jPanel8);

        jb_guardarProfesional.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jb_guardarProfesional.setText("Guardar");
        jb_guardarProfesional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarProfesionalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_datosProfesionalesLayout = new javax.swing.GroupLayout(jd_datosProfesionales.getContentPane());
        jd_datosProfesionales.getContentPane().setLayout(jd_datosProfesionalesLayout);
        jd_datosProfesionalesLayout.setHorizontalGroup(
            jd_datosProfesionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtb_datosProfesionales)
            .addGroup(jd_datosProfesionalesLayout.createSequentialGroup()
                .addGroup(jd_datosProfesionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_datosProfesionalesLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel24))
                    .addGroup(jd_datosProfesionalesLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jb_guardarProfesional)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_datosProfesionalesLayout.setVerticalGroup(
            jd_datosProfesionalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_datosProfesionalesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtb_datosProfesionales, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_guardarProfesional)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jd_menuAgencia.setTitle("Menú");

        jLabel47.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel47.setText("Menú Principal");

        jb_crearEmpresa.setText("Crear nueva empresa");
        jb_crearEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_crearEmpresaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_menuAgenciaLayout = new javax.swing.GroupLayout(jd_menuAgencia.getContentPane());
        jd_menuAgencia.getContentPane().setLayout(jd_menuAgenciaLayout);
        jd_menuAgenciaLayout.setHorizontalGroup(
            jd_menuAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuAgenciaLayout.createSequentialGroup()
                .addGroup(jd_menuAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_menuAgenciaLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel47))
                    .addGroup(jd_menuAgenciaLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jb_crearEmpresa)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jd_menuAgenciaLayout.setVerticalGroup(
            jd_menuAgenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_menuAgenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addGap(42, 42, 42)
                .addComponent(jb_crearEmpresa)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        jd_crearEmpresa.setTitle("Crear Empresa");

        jLabel48.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel48.setText("Datos de la empresa");

        jLabel49.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel49.setText("CIF");

        jLabel50.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel50.setText("Nombre");

        jLabel51.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel51.setText("CEO");

        jLabel52.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel52.setText("Dirección");

        jLabel53.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel53.setText("Categoría");

        jtf_cifEmpresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_nombreEmpresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_ceoEmpresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jta_direccionEmpresa.setColumns(20);
        jta_direccionEmpresa.setRows(5);
        jScrollPane5.setViewportView(jta_direccionEmpresa);

        jcb_categoriaEmpresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_categoriaEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administración", "Finanzas", "Call Center", "Informática", "Mantenimiento", "Restuarante", "Salud" }));

        jb_guardarEmpresas.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jb_guardarEmpresas.setText("Guardar");
        jb_guardarEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarEmpresasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_crearEmpresaLayout = new javax.swing.GroupLayout(jd_crearEmpresa.getContentPane());
        jd_crearEmpresa.getContentPane().setLayout(jd_crearEmpresaLayout);
        jd_crearEmpresaLayout.setHorizontalGroup(
            jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearEmpresaLayout.createSequentialGroup()
                .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_crearEmpresaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crearEmpresaLayout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jd_crearEmpresaLayout.createSequentialGroup()
                                    .addComponent(jLabel49)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                    .addComponent(jtf_cifEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_crearEmpresaLayout.createSequentialGroup()
                                    .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel50)
                                        .addComponent(jLabel51))
                                    .addGap(18, 18, 18)
                                    .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtf_nombreEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addComponent(jtf_ceoEmpresa))))
                            .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jb_guardarEmpresas)
                                .addGroup(jd_crearEmpresaLayout.createSequentialGroup()
                                    .addComponent(jLabel53)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jcb_categoriaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jd_crearEmpresaLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel48)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jd_crearEmpresaLayout.setVerticalGroup(
            jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crearEmpresaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crearEmpresaLayout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(35, 35, 35)
                        .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(jtf_cifEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel50))
                    .addComponent(jtf_nombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(jtf_ceoEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52))
                .addGap(15, 15, 15)
                .addGroup(jd_crearEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel53)
                    .addComponent(jcb_categoriaEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jb_guardarEmpresas)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_subecurriculum.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jb_subecurriculum.setText("Sube tu currículum");
        jb_subecurriculum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_subecurriculumMouseClicked(evt);
            }
        });
        getContentPane().add(jb_subecurriculum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Imagen9.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 31, 619, 311));

        jToolBar2.setRollover(true);

        jb_login.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jb_login.setText("Login");
        jb_login.setFocusable(false);
        jb_login.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jb_login.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jb_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_loginMouseClicked(evt);
            }
        });
        jToolBar2.add(jb_login);

        getContentPane().add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 619, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_loginMouseClicked
        jd_login.pack();
        jd_login.setModal(true);
        jd_login.setLocationRelativeTo(this);
        jd_login.setVisible(true);
    }//GEN-LAST:event_jb_loginMouseClicked

    private void jb_aceptarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_aceptarLoginMouseClicked
        boolean condicion = false;
        condicion = validarEspacio();
        if (condicion) {
            JOptionPane.showMessageDialog(this, "Los campos no pueden quedar vacíos");
        } else {
            String contrasena = new String(jpf_contrasena.getPassword());
            if (jtf_usuario.getText().equalsIgnoreCase("agencia") && contrasena.equalsIgnoreCase("123")) {
                jd_menuAgencia.pack();
                jd_menuAgencia.setModal(true);
                jd_login.setVisible(false);
                jd_menuAgencia.setLocationRelativeTo(this);
                jd_menuAgencia.setVisible(true);
                jpf_contrasena.setText("");
                jtf_usuario.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o constraseña incorrecto");
            }

        }
    }//GEN-LAST:event_jb_aceptarLoginMouseClicked

    private void jb_salirLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirLoginMouseClicked
        jd_login.setVisible(false);
    }//GEN-LAST:event_jb_salirLoginMouseClicked

    private void jb_subecurriculumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_subecurriculumMouseClicked
        jd_datosPersonales.pack();
        jd_datosPersonales.setModal(true);
        jd_datosPersonales.setLocationRelativeTo(this);
        jd_datosPersonales.setVisible(true);
    }//GEN-LAST:event_jb_subecurriculumMouseClicked

    private void jb_guardarPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarPersonalMouseClicked
        String genero = "", id = "";
        boolean edad, antecedentes, licencia, servicio, casado, visa;
        if (jrb_femeninoPersonal.isSelected()) {
            genero = "F";
        } else {
            genero = "M";
        }
        persona = new Persona(jtf_identidadLegal.getText(), jtf_nombrePersonal.getText(), jtf_apellidoPersonal.getText(), jtf_nacionalidadPersonal.getText(), genero,
                jdc_nacimientoPersonal.getDate(), jtf_telefonoPersonal.getText(), jtf_correoPersonal.getText(), jta_direccionPersonal.getText());
        if (jrb_siFamiliares.isSelected()) {
            id = jtf_idFamiliares.getText();
        } else {
            id = "0";
        }
        edad = jrb_siEdadLegal.isSelected();
        antecedentes = jrb_siAntecedenteLegal.isSelected();
        licencia = jrb_siLicenciaLegal.isSelected();
        servicio = jrb_siServicioLegal.isSelected();
        casado = jrb_siCasadoLegal.isSelected();
        visa = jrb_siVisaLegal.isSelected();
        persona.getFamiliares().add(new DatosFamiliares(jtf_nombreFamiliares.getText(), jtf_parentescoFamiliares.getText(), id));
        datosLegales = new DatosLegales(jtf_identidadLegal.getText(), edad, antecedentes, licencia, servicio, casado, visa);
        persona.setDatoslegales(datosLegales);
        jd_datosProfesionales.pack();
        jd_datosProfesionales.setModal(true);
        jd_datosProfesionales.setLocationRelativeTo(this);
        jd_datosPersonales.setVisible(false);
        jd_datosProfesionales.setVisible(true);
    }//GEN-LAST:event_jb_guardarPersonalMouseClicked

    public void resetearValores() {
        jtf_identidadLegal.setText("");
        jtf_nombrePersonal.setText("");
        jtf_apellidoPersonal.setText("");
        jtf_nacionalidadPersonal.setText("");
        jtf_telefonoPersonal.setText("");
        jtf_correoPersonal.setText("");
        jta_direccionPersonal.setText("");
        jtf_nombreFamiliares.setText("");
        jtf_parentescoFamiliares.setText("");
        jtf_idFamiliares.setText("");
        jta_puestoProfesional.setText("");
        jta_idiomasProfesional.setText("");
        jtf_salarioProfesional.setText("");
        jtf_especializacionProfesional.setText("");
        jta_otrosEstudiosProfesional.setText("");
        jcb_gradoProfesional.setSelectedIndex(0);
    }

    private void jb_guardarProfesionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarProfesionalMouseClicked
        //Curriculum
        int salario = Integer.parseInt(jtf_salarioProfesional.getText());
        boolean contrato = jrb_siContratoProfesional.isSelected();
        curriculum = new Curriculum(salario, contrato);
        String puestos = jta_puestoProfesional.getText();
        String idiomas = jta_idiomasProfesional.getText();
        String[] puestosSeparados = puestos.split(",");
        String[] idiomasSeparados = idiomas.split(",");
        curriculum.getPuestoDeseado().addAll(Arrays.asList(puestosSeparados));
        curriculum.getIdiomas().addAll(Arrays.asList(idiomasSeparados));

        //Experiencia Laboral
        int aniosExperiencia = Integer.parseInt(jtf_salarioProfesional.getText());
        experiencia = new ExperienciaLaboral(aniosExperiencia, jtf_trabajoProfesional.getText(), jtf_puestoProfesional.getText());

        //Datos Académicos
        String grado;
        boolean estudiante = jrb_siEstudianteProfesional.isSelected();
        if (jcb_gradoProfesional.getSelectedIndex() == 0) {
            grado = "Basica";
        } else if (jcb_gradoProfesional.getSelectedIndex() == 1) {
            grado = "Secundaria";
        } else if (jcb_gradoProfesional.getSelectedIndex() == 2) {
            grado = "Licenciatura o Ingenieria";
        } else if (jcb_gradoProfesional.getSelectedIndex() == 3) {
            grado = "Maestria";
        } else {
            grado = "Doctorado";
        }
        String especializacion;
        if (jtf_especializacionProfesional.getText() == null) {
            especializacion = "Ninguna";
        } else {
            especializacion = jtf_especializacionProfesional.getText();
        }
        datosacademicos = new DatosAcademicos(grado, especializacion, estudiante, jta_otrosEstudiosProfesional.getText());

        //Datos sanitarios
        boolean alergias = jrb_siAlergiasProfesional.isSelected();
        boolean respiratorio = jrb_siRespiratorioProfesional.isSelected();
        boolean cardiaco = jrb_siCardiacoProfesional.isSelected();
        boolean mental = jrb_siMentalProfesional.isSelected();
        datossanitarios = new DatosSanitarios(alergias, respiratorio, cardiaco, mental);

        //lo último
        persona.setCurriculum(curriculum);
        persona.setExperiencia(experiencia);
        persona.setDatosacademicos(datosacademicos);
        persona.setDatossanitarios(datossanitarios);
        resetearValores();
        jd_datosProfesionales.setVisible(false);
        JOptionPane.showMessageDialog(this, "Se han guardado tus datos");
    }//GEN-LAST:event_jb_guardarProfesionalMouseClicked

    private void jb_crearEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_crearEmpresaMouseClicked
        jd_crearEmpresa.pack();
        jd_crearEmpresa.setModal(true);
        jd_crearEmpresa.setLocationRelativeTo(this);
        jd_menuAgencia.setVisible(false);
        jd_crearEmpresa.setVisible(true);
    }//GEN-LAST:event_jb_crearEmpresaMouseClicked

    private void jb_guardarEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarEmpresasMouseClicked
        String categoria;
        if (jcb_categoriaEmpresa.getSelectedIndex() == 0) {
            categoria = "Administracion";
        } else if (jcb_categoriaEmpresa.getSelectedIndex() == 1) {
            categoria = "Finanzas";
        } else if (jcb_categoriaEmpresa.getSelectedIndex() == 2) {
            categoria = "Call Center";
        } else if (jcb_categoriaEmpresa.getSelectedIndex() == 3) {
            categoria = "Informatica";
        } else if (jcb_categoriaEmpresa.getSelectedIndex() == 4) {
            categoria = "Mantenimiento";
        } else if (jcb_categoriaEmpresa.getSelectedIndex() == 5) {
            categoria = "Restuarante";
        } else {
            categoria = "Salud";
        }
        empresa = new Empresas(jtf_cifEmpresa.getText(), jtf_nombreEmpresa.getText(), jtf_ceoEmpresa.getText(), jta_direccionEmpresa.getText(), categoria);
        jtf_cifEmpresa.setText("");
        jtf_nombreEmpresa.setText("");
        jtf_ceoEmpresa.setText("");
        jta_direccionEmpresa.setText("");
        jcb_categoriaEmpresa.setSelectedIndex(0);
        JOptionPane.showMessageDialog(this, "La empresa ha sido guardada exitosamente");
        jd_crearEmpresa.setVisible(false);
        jd_menuAgencia.setVisible(true);
    }//GEN-LAST:event_jb_guardarEmpresasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
            //this is a random comment
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_alergia;
    private javax.swing.ButtonGroup bg_antecedentePenal;
    private javax.swing.ButtonGroup bg_cardiaco;
    private javax.swing.ButtonGroup bg_casado;
    private javax.swing.ButtonGroup bg_contrato;
    private javax.swing.ButtonGroup bg_estudiante;
    private javax.swing.ButtonGroup bg_licencia;
    private javax.swing.ButtonGroup bg_mayor;
    private javax.swing.ButtonGroup bg_mental;
    private javax.swing.ButtonGroup bg_respiratorio;
    private javax.swing.ButtonGroup bg_servicioMilitar;
    private javax.swing.ButtonGroup bg_visa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jb_aceptarLogin;
    private javax.swing.JButton jb_crearEmpresa;
    private javax.swing.JButton jb_guardarEmpresas;
    private javax.swing.JButton jb_guardarPersonal;
    private javax.swing.JButton jb_guardarProfesional;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_salirLogin;
    private javax.swing.JButton jb_subecurriculum;
    private javax.swing.JComboBox<String> jcb_categoriaEmpresa;
    private javax.swing.JComboBox<String> jcb_gradoProfesional;
    private javax.swing.JDialog jd_crearEmpresa;
    private javax.swing.JDialog jd_datosPersonales;
    private javax.swing.JDialog jd_datosProfesionales;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_menuAgencia;
    private com.toedter.calendar.JDateChooser jdc_nacimientoPersonal;
    private javax.swing.JPasswordField jpf_contrasena;
    private javax.swing.JRadioButton jrb_femeninoPersonal;
    private javax.swing.JRadioButton jrb_masculinoPersonal;
    private javax.swing.JRadioButton jrb_noAlergiasProfesional;
    private javax.swing.JRadioButton jrb_noAntecedenteLegal;
    private javax.swing.JRadioButton jrb_noCardiacoProfesional;
    private javax.swing.JRadioButton jrb_noCasadoLegal;
    private javax.swing.JRadioButton jrb_noContratoProfesional;
    private javax.swing.JRadioButton jrb_noEdadLegal;
    private javax.swing.JRadioButton jrb_noEstudianteProfesional;
    private javax.swing.JRadioButton jrb_noFamiliares;
    private javax.swing.JRadioButton jrb_noLicenciaLegal;
    private javax.swing.JRadioButton jrb_noMentalProfesional;
    private javax.swing.JRadioButton jrb_noRespiratorioProfesional;
    private javax.swing.JRadioButton jrb_noServicioLegal;
    private javax.swing.JRadioButton jrb_noVisaLegal;
    private javax.swing.JRadioButton jrb_siAlergiasProfesional;
    private javax.swing.JRadioButton jrb_siAntecedenteLegal;
    private javax.swing.JRadioButton jrb_siCardiacoProfesional;
    private javax.swing.JRadioButton jrb_siCasadoLegal;
    private javax.swing.JRadioButton jrb_siContratoProfesional;
    private javax.swing.JRadioButton jrb_siEdadLegal;
    private javax.swing.JRadioButton jrb_siEstudianteProfesional;
    private javax.swing.JRadioButton jrb_siFamiliares;
    private javax.swing.JRadioButton jrb_siLicenciaLegal;
    private javax.swing.JRadioButton jrb_siMentalProfesional;
    private javax.swing.JRadioButton jrb_siRespiratorioProfesional;
    private javax.swing.JRadioButton jrb_siServicioLegal;
    private javax.swing.JRadioButton jrb_siVisaLegal;
    private javax.swing.JTextArea jta_direccionEmpresa;
    private javax.swing.JTextArea jta_direccionPersonal;
    private javax.swing.JTextArea jta_idiomasProfesional;
    private javax.swing.JTextArea jta_otrosEstudiosProfesional;
    private javax.swing.JTextArea jta_puestoProfesional;
    private javax.swing.JTabbedPane jtb_datosProfesionales;
    private javax.swing.JTextField jtf_aniosProfesional;
    private javax.swing.JTextField jtf_apellidoPersonal;
    private javax.swing.JTextField jtf_ceoEmpresa;
    private javax.swing.JTextField jtf_cifEmpresa;
    private javax.swing.JTextField jtf_correoPersonal;
    private javax.swing.JTextField jtf_especializacionProfesional;
    private javax.swing.JTextField jtf_idFamiliares;
    private javax.swing.JTextField jtf_identidadLegal;
    private javax.swing.JTextField jtf_nacionalidadPersonal;
    private javax.swing.JTextField jtf_nombreEmpresa;
    private javax.swing.JTextField jtf_nombreFamiliares;
    private javax.swing.JTextField jtf_nombrePersonal;
    private javax.swing.JTextField jtf_nombrePersonal1;
    private javax.swing.JTextField jtf_parentescoFamiliares;
    private javax.swing.JTextField jtf_puestoProfesional;
    private javax.swing.JTextField jtf_salarioProfesional;
    private javax.swing.JTextField jtf_telefonoPersonal;
    private javax.swing.JTextField jtf_trabajoProfesional;
    private javax.swing.JTextField jtf_usuario;
    private javax.swing.JTabbedPane jtp_informacionPersonal;
    // End of variables declaration//GEN-END:variables
ArrayList<Persona> personas= new ArrayList();
ArrayList<TipoTrabajo> tiposdetrabajo= new ArrayList();
ArrayList<Empresas> empresas= new ArrayList();
DriverDB servidor=new DriverDB();
}
